server:
  port: 8030

spring:
  application:
    name: demo-feign

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置 nacos 注册中心地址
        cluster-name: ShangHai
        metadata:
          version: v1

# 饥饿加载
ribbon:
  eager-load:
    # 开启 ribbon 饥饿加载
    enabled: true
    # 配置 mall-user 使用饥饿加载，多个使用逗号分隔
    clients: mall-account

# 开启 feign 日志的话，需要将日志级别设置为 debug
logging:
  level:
    org:
      example:
        feign: DEBUG


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#  client:
#    config:
#      mall-account:
#        # 局部日志文件配置
#        loggerLevel: FULL
#        # 超时配置
#        # 连接超时，默认 2s
#        connectTimeout: 5000
#        # 请求处理超时：默认 5s
#        readTimeout: 10000
  # 配置 GZIP 来压缩数据（不支持 OkHttp）
  compression:
    request:
      enabled: true
      # 配置压缩类型
      mime-types: "text/xml", "application/xml", "application/json"
      # 最小压缩值
      min-request-size: 2048
    response:
      enabled: true
