server:
  port: 8011

spring:
  application:
    name: mall-user

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置 nacos 注册中心地址
        cluster-name: BeiJing
        metadata:
          version: v2