server:
  port: 8081

spring:
  application:
    name: product-service

  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
      session-timeout: 30000