// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package org.example.protobuf.proto;

public interface BuyerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protobuf.proto.Buyer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buyerId = 1;</code>
   * @return The buyerId.
   */
  int getBuyerId();
}
