// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package org.example.protobuf.proto;

public final class OrderServiceApi {
  private OrderServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protobuf_proto_Buyer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protobuf_proto_Buyer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protobuf_proto_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protobuf_proto_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013order.proto\022\032org.example.protobuf.prot" +
      "o\"\030\n\005Buyer\022\017\n\007buyerId\030\001 \001(\005\"S\n\005Order\022\017\n\007" +
      "orderId\030\001 \001(\005\022\021\n\tproductId\030\002 \001(\005\022\021\n\torde" +
      "rTime\030\003 \001(\003\022\023\n\013buyerMarker\030\004 \001(\t2f\n\014Orde" +
      "rService\022V\n\nlistOrders\022!.org.example.pro" +
      "tobuf.proto.Buyer\032!.org.example.protobuf" +
      ".proto.Order\"\0000\001B/\n\032org.example.protobuf" +
      ".protoB\017OrderServiceApiP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_protobuf_proto_Buyer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_protobuf_proto_Buyer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protobuf_proto_Buyer_descriptor,
        new String[] { "BuyerId", });
    internal_static_org_example_protobuf_proto_Order_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_protobuf_proto_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protobuf_proto_Order_descriptor,
        new String[] { "OrderId", "ProductId", "OrderTime", "BuyerMarker", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
