// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package org.example.protobuf.proto;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protobuf.proto.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderId = 1;</code>
   * @return The orderId.
   */
  int getOrderId();

  /**
   * <code>int32 productId = 2;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>int64 orderTime = 3;</code>
   * @return The orderTime.
   */
  long getOrderTime();

  /**
   * <code>string buyerMarker = 4;</code>
   * @return The buyerMarker.
   */
  String getBuyerMarker();
  /**
   * <code>string buyerMarker = 4;</code>
   * @return The bytes for buyerMarker.
   */
  com.google.protobuf.ByteString
      getBuyerMarkerBytes();
}
