// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.example.protobuf.proto;

public final class RPCDataServiceApi {
  private RPCDataServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protobuf_proto_RPCDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protobuf_proto_RPCDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protobuf_proto_RPCDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protobuf_proto_RPCDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\032org.example.protobuf" +
      ".proto\"\"\n\016RPCDataRequest\022\020\n\010userName\030\001 \001" +
      "(\t\"D\n\017RPCDataResponse\022\014\n\004code\030\001 \001(\005\022\022\n\ns" +
      "erverData\030\002 \001(\t\022\017\n\007message\030\003 \001(\t2v\n\016RPCD" +
      "ataService\022d\n\007getData\022*.org.example.prot" +
      "obuf.proto.RPCDataRequest\032+.org.example." +
      "protobuf.proto.RPCDataResponse\"\000B1\n\032org." +
      "example.protobuf.protoB\021RPCDataServiceAp" +
      "iP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_protobuf_proto_RPCDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_protobuf_proto_RPCDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protobuf_proto_RPCDataRequest_descriptor,
        new String[] { "UserName", });
    internal_static_org_example_protobuf_proto_RPCDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_protobuf_proto_RPCDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protobuf_proto_RPCDataResponse_descriptor,
        new String[] { "Code", "ServerData", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
