// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.example.protobuf.proto;

public interface RPCDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protobuf.proto.RPCDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
