// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.example.protobuf.proto;

public interface RPCDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protobuf.proto.RPCDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string serverData = 2;</code>
   * @return The serverData.
   */
  String getServerData();
  /**
   * <code>string serverData = 2;</code>
   * @return The bytes for serverData.
   */
  com.google.protobuf.ByteString
      getServerDataBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
