server:
  port: 8088

spring:
  application:
    name: spring-cloud-dubbo-provider
  main:
    # spring boot 2.1 以上需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: ${spring.application.name}
  scan:
    # 指定 dubbo 服务实现类的扫描基准包
    base-packages: org.example.demo.dubbo.provider.service

#  protocol:
#    # dubbo 协议（使用 netty 作为服务器）
#    name: dubbo
#    # dubbo 协议端口，-1 表示自增端口，从 20880 开始绑定
#    port: -1

  protocols:
    p1:
      id: dubbo1
      name: dubbo
      port: 20881
      host: 0.0.0.0
    p2:
      id: dubbo2
      name: dubbo
      port: 20882
      host: 0.0.0.0
    p3:
      id: dubbo3
      name: rest
      port: 20883
      host: 0.0.0.0

  registry:
    # 指定 dubbo 注册中心地址
    address: zookeeper://127.0.0.1:2181