server:
  port: 8080

dubbo:
  scan:
    # 指定 dubbo 服务实现类的扫描基准包
    base-packages: org.example.demo.dubbo.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口，-1 表示自增端口，从 20880 开始绑定
    port: -1

spring:
  application:
    name: spring-cloud-dubbo-provider
  main:
    # spring boot 2.1 以上需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
