server:
  port: 8010
#  servlet:
#    context-path: /hello

spring:
  application:
    name: mall-user

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置 nacos 注册中心地址
        cluster-name: ShangHai
        metadata:
          version: v1

    sentinel:
      transport:
        # 指定 sentinel 控制台地址
        dashboard: 127.0.0.1:8080
        # 指定应用与 sentinel 控制台交互的端口（默认：8719），应用本地会启动该端口占用 HttpServer
#        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: '*'