spring:
  application:
    name: local-grpc-client

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置 nacos 注册中心地址

server:
  port: 8090

grpc:
  client:
    # grpc 配置的名字，GrpcClient 会使用
    local-grpc-server:
      # 指定服务端 grpc.server.port 的值
      # 使用注册中心的场景下，这段话需要删除，交给注册中心来调度
#      address: static://127.0.0.1:9090
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
